### ISSUE TITLE
Is there a way to add columns from arrays?

### ISSUE THREAD

**Issue by franciscoGPS** [naqvis/CrysDA#2]
I'm thinking on something like this: 
`    df = Crysda.dataframe_of("col_1").values(["1","2", "3"])
    pp df
 Prints: 
 Crysda::SimpleDataFrame(
 @cols=
  [Crysda::StringCol(
    @name="col_1",
    @values=["1", "2", "3"])
    ])
    
df.add_column("other_col", ["4","5", "6"]) 
pp df

 Prints: 
 Crysda::SimpleDataFrame(
 @cols=
  [Crysda::StringCol(
    @name="col_1",
    @values=["1", "2", "3"]),
   Crysda::StringCol(
    @name="other_col",
    @values=["4", "5", "6"]),
    ])
 `
Or maybe I'm missing something to accomplish this?
Thank you so much. This is an awesome shard.

**Comment by naqvis** [comment]
Hi @franciscoGPS , not sure if I understand your question properly. But if you are asking to load values from Array then doesn't they work out of the box?

```crystal
df = Crysda.dataframe_of("col_1").values(["1","2", "3"])
puts df.schema
```
```sh
DataFrame with 3 observations
col_1 [String] 1, 2, 3
```
```crystal
df.print
```
```sh
A DataFrame: 3 x 1
    col_1
1       1
2       2
3       3
```

**Comment by franciscoGPS** [comment]
Thank you very much for the quick response. 
That example you show does work, but I don't see a way to dinamically append a new column (assuming it is same size).

After your example, is there a way to add a new column to `df` next to `col_1` with same size so it becomes `A DataFrame 3 x 2` ?

**Comment by naqvis** [comment]
Yes, you can add column to dataframe. 

```crystal
df = df.add_column("col_2"){["4","5","6"]}
puts df.schema
```
```sh
DataFrame with 3 observations
col_1 [String] 1, 2, 3
col_2 [String] 4, 5, 6
```
```crystal
df.print
```
```sh
A DataFrame: 3 x 2
    col_1   col_2
1       1       4
2       2       5
3       3       6
```

**Comment by franciscoGPS** [comment]
Oh, wow. I didn't see that coming. Thank you so much @naqvis .
